package pojo;
// Generated Oct 21, 2020 1:23:40 AM by Hibernate Tools 4.3.1
import dao.daoAD;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;


/**
 * Admin generated by hbm2java
 */
@ManagedBean
public class Admin  implements java.io.Serializable {

    private String message;
     private String admin;
     private String password;

    public Admin() {
    }
    
    public Admin(String admin, String password) {
       this.admin = admin;
       this.password = password;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
    
   
    public String getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(String admin) {
        this.admin = admin;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
     public String validatelogin(){
        daoAD udao = new daoAD();
        List<Admin> us = udao.validateLogin(admin, password);
       if(us != null){
            if(us.size() == 1){
                admin = us.get(0).admin;
                password = us.get(0).password;
                return "welcome_admin";
            }
            else{
                this.message = "gagal login";
                return "loginError";
            }
              
        }
       this.message="Gagal Login";
       return"loginError";
      }
//    public String validatelogin()
//    { 
//        try {
//            daoAD pdao=new daoAD();
//            List<Admin> prod=pdao.validateLogin(admin, password);
//            admin=prod.get(0).admin;
//            password=prod.get(0).password;
//            
//            FacesContext context = FacesContext.getCurrentInstance();
//            if(admin != null) {
//                context.getExternalContext().getSessionMap().put("admin", admin);
//                return "admin_createBerita";
//            }
//            else {
//                return "loginError";
//            }
//        }
//        catch(Exception ex) {
//            return "loginError";
//        }
//    }
}