package pojo;
// Generated Oct 24, 2020 11:44:40 PM by Hibernate Tools 4.3.1
import dao.daoJA;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;


/**
 * Jadwal generated by hbm2java
 */
@ManagedBean
public class Jadwal  implements java.io.Serializable {


     private int kodeJadwal;
     private String senin;
     private String selasa;
     private String rabu;
     private String kamis;
     private String jumat;
     private String sabtu;
     private String minggu;
     private String message;

    public Jadwal() {
    }

    public Jadwal(int kodeJadwal, String senin, String selasa, String rabu, String kamis, String jumat, String sabtu, String minggu) {
       this.kodeJadwal = kodeJadwal;
       this.senin = senin;
       this.selasa = selasa;
       this.rabu = rabu;
       this.kamis = kamis;
       this.jumat = jumat;
       this.sabtu = sabtu;
       this.minggu = minggu;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
   
    
    public int getKodeJadwal() {
        return this.kodeJadwal;
    }
    
    public void setKodeJadwal(int kodeJadwal) {
        this.kodeJadwal = kodeJadwal;
    }
    public String getSenin() {
        return this.senin;
    }
    
    public void setSenin(String senin) {
        this.senin = senin;
    }
    public String getSelasa() {
        return this.selasa;
    }
    
    public void setSelasa(String selasa) {
        this.selasa = selasa;
    }
    public String getRabu() {
        return this.rabu;
    }
    
    public void setRabu(String rabu) {
        this.rabu = rabu;
    }
    public String getKamis() {
        return this.kamis;
    }
    
    public void setKamis(String kamis) {
        this.kamis = kamis;
    }
    public String getJumat() {
        return this.jumat;
    }
    
    public void setJumat(String jumat) {
        this.jumat = jumat;
    }
    public String getSabtu() {
        return this.sabtu;
    }
    
    public void setSabtu(String sabtu) {
        this.sabtu = sabtu;
    }
    public String getMinggu() {
        return this.minggu;
    }
    
    public void setMinggu(String minggu) {
        this.minggu = minggu;
    }
    
    public void save()
    {
        daoJA pdao=new daoJA();
        pdao.addJadwal(this);
        kodeJadwal=0;
        senin = "";
        selasa = "";
        rabu ="";
        kamis = "";
        jumat="";
        sabtu="";
        minggu="";
    }

    public void delete()
    {    
        daoJA pdao=new daoJA();
        pdao.deleteJadwal(kodeJadwal);
        kodeJadwal=0;
        senin = "";
        selasa = "";
        rabu ="";
        kamis = "";
        jumat="";
        sabtu="";
        minggu="";
        this.message="data dihapus";
    }

    public String getbyid()
    { 
        daoJA pdao=new daoJA();
        List<Jadwal> prod=pdao.getbyID(kodeJadwal);
        if(prod != null){
            if(prod.size() == 1){
                senin=prod.get(0).senin;
                selasa=prod.get(0).selasa;
                rabu=prod.get(0).rabu;
                kamis=prod.get(0).kamis;
                jumat=prod.get(0).jumat;
                sabtu=prod.get(0).sabtu;
                minggu=prod.get(0).minggu;
                this.message = "data ditemukan";
                return "admin_updelJadwal";
            }else{
                this.message = "data kosong";
                senin = "";
                selasa = "";
                rabu ="";
                kamis = "";
                jumat="";
                sabtu="";
                minggu="";
                }  
        }   
        return "admin_updelJadwal";
    }

    public List<Jadwal> getallrecords()
    {
        daoJA pdao=new daoJA();
        List<Jadwal> prod=pdao.retrieveJadwal();
        return prod;
    }

    public void update()
    {
        daoJA pdao=new daoJA();
        pdao.updateJadwal(this);
        kodeJadwal=0;
        senin = "";
        selasa = "";
        rabu ="";
        kamis = "";
        jumat="";
        sabtu="";
        minggu="";
        this.message="data diubah";
    }
}


