package pojo;
// Generated Oct 24, 2020 11:44:40 PM by Hibernate Tools 4.3.1
import dao.daoTI;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;


/**
 * Tiket generated by hbm2java
 */
@ManagedBean
public class Tiket  implements java.io.Serializable {


     private int kodeTiket;
     private String reguler;
     private String premium;
     private String annualPas;
     private String message;

    public Tiket() {
    }

    public Tiket(int kodeTiket, String reguler, String premium, String annualPas) {
       this.kodeTiket = kodeTiket;
       this.reguler = reguler;
       this.premium = premium;
       this.annualPas = annualPas;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
   
    public int getKodeTiket() {
        return this.kodeTiket;
    }
    
    public void setKodeTiket(int kodeTiket) {
        this.kodeTiket = kodeTiket;
    }
    public String getReguler() {
        return this.reguler;
    }
    
    public void setReguler(String reguler) {
        this.reguler = reguler;
    }
    public String getPremium() {
        return this.premium;
    }
    
    public void setPremium(String premium) {
        this.premium = premium;
    }
    public String getAnnualPas() {
        return this.annualPas;
    }
    
    public void setAnnualPas(String annualPas) {
        this.annualPas = annualPas;
    }
    
    public void save()
    {
        daoTI pdao=new daoTI();
        pdao.addTiket(this);
        kodeTiket=0;
        reguler="";
        premium="";
        annualPas="";
    }

    public void delete()
    {    
        daoTI pdao=new daoTI();
        pdao.deleteTiket(kodeTiket);
        kodeTiket=0;
         reguler="";
        premium="";
        annualPas="";
        this.message="data dihapus";
    }

    public String getbyid()
    { 
        daoTI pdao=new daoTI();
        List<Tiket> prod=pdao.getbyID(kodeTiket);
        if(prod != null){
            if(prod.size() == 1){
                reguler=prod.get(0).reguler;
                premium=prod.get(0).premium;
                annualPas=prod.get(0).annualPas;
                this.message = "data ditemukan";
               return "admin_updelTiket";
            }else{
                this.message = "data kosong";
                reguler="";
                premium="";
                annualPas="";
                }  
        }   
        return "admin_updelTiket";
    }

    public List<Tiket> getallrecords()
    {
        daoTI pdao=new daoTI();
        List<Tiket> prod=pdao.retrieveTiket();
        return prod;
    }

    public void update()
    {
        daoTI pdao=new daoTI();
        pdao.updateTiket(this);
        kodeTiket=0;
         reguler="";
        premium="";
        annualPas="";
        this.message="data diubah";
    }
}


