package pojo;
// Generated Oct 21, 2020 1:23:40 AM by Hibernate Tools 4.3.1
import dao.daoWA;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;


/**
 * Wahana generated by hbm2java
 */
@ManagedBean
public class Wahana  implements java.io.Serializable {

    private String message;
     private int kodeWahana;
     private String namaWahana;

    public Wahana() {
    }

    public Wahana(int kodeWahana, String namaWahana) {
       this.kodeWahana = kodeWahana;
       this.namaWahana = namaWahana;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
   
    public int getKodeWahana() {
        return this.kodeWahana;
    }
    
    public void setKodeWahana(int kodeWahana) {
        this.kodeWahana = kodeWahana;
    }
    public String getNamaWahana() {
        return this.namaWahana;
    }
    
    public void setNamaWahana(String namaWahana) {
        this.namaWahana = namaWahana;
    }

    public void save()
    {
        daoWA pdao=new daoWA();
        pdao.addWahana(this);
        kodeWahana=0;
        namaWahana="";
    }

    public void delete()
    {    
        daoWA pdao=new daoWA();
        pdao.deleteWahana(kodeWahana);
       kodeWahana=0;
        namaWahana="";
        this.message="data dihapus";
    }

    public String getbyid()
    { 
        daoWA pdao=new daoWA();
        List<Wahana> prod=pdao.getbyID(kodeWahana);
        if(prod != null){
            if(prod.size() == 1){
                kodeWahana=prod.get(0).kodeWahana;
                namaWahana=prod.get(0).namaWahana;
                this.message = "data ditemukan";
                return "admin_updelWahana";
            }else{
                this.message = "data kosong";
                namaWahana="";
                }  
        }   
        return "admin_updelWahana";
    }

    public List<Wahana> getallrecords()
    {
        daoWA pdao=new daoWA();
        List<Wahana> prod=pdao.retrieveWahana();
        return prod;
    }

    public void update()
    {
        daoWA pdao=new daoWA();
        pdao.updateWahana(this);
        kodeWahana=0;
        namaWahana="";
        this.message="data diubah";
    }
}


